# Site settings
baseurl = "https://adam-reinschmidt.netlify.com/"
languageCode = "en-us"
title = "Highlights"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[social]

    linkedin = "https://www.linkedin.com/in/adam-reinschmidt-920355158"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Font-Awesome's icon font. Look at fontawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engines. Feel free to add more information.
  # These lines will be inserted as meta tags.
  name = "Adam Reinschmidt"
  description = "An introductory and contact site for cellist and student Adam Reinschmidt."

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "ajrcellist@gmail.com"


  # If this param is set to true, every section gets its own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.png and overlay.png to set the background.
  backgroundpersection = true

  # Hero Section
  [params.hero]
    title = "Highlights"
    description = "A Profile of Adam Reinschmidt"
    buttontext = "begin"

  # about section
  [params.about]
    enable = true
    title = "Who am I"
    description = "My name is Adam Reinschmidt, and I am a cellist and student at the New College of Florida in Sarasota, FL. I have been playing the cello for over 10 years; in addition, I have played piano for 11 years and sung in upper-level high school and collegiate choirs for nearly 3 years. I attended Roseville Area High School in Minnesota, where I played in our school's top Symphony Orchestra, as well as the Chamber Orchestra and multiple smaller ensembles. Over 3 years, I was among the top 3 seated cellists every time, and during my senior year served as the Principle Cellist and section leader. During this time, I had the opportunity to perform 2 featured solos: the first movement of Antonin Dvorak's Serenade for Strings in E Major, Op. 22, and an arrangement of Ralph Vaughan Williams' Fantasia on Greensleaves for Solo Cello, Flute, Harp and Chamber Orchestra."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "adam_grad_cello.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "Stuff I do"
    description = "I'm currently in my 2nd year at the New College of Florida, and I plan to major in both Biology and Environmental Studies. I still remain very active in the college music program, however; I sing bass/baritone in the New College Chorus, and I helped found the New College Chamber Music Group, where I play both piano and cello. Outside of music performence and academics, I'm a voracious music, film and video game nerd; I love to read books and magezines, especially Smithsonian and works by Cormac McCarthy, John Steinbeck, John Muir, and Michael Crichton. I love camping, hiking, canoeing, and anything else that gets met into the wilderness."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "widjiAE_centershot.jpg"

    [[params.skills]]
      icon = "fa-university"
      title = "Student"
      description = "New College of Florida"

    [[params.skills]]
      icon = "fa-graduation-cap"
      title = "Acedemic Plans"
      description = "Planning on double-concentration in Biology and Environmental Studies"

    [[params.skills]]
      icon = "fa-tree"
      title = "Wilderness"
      description = "I am also a wilderness enthusiast- I love camping, hiking, canoeing, etc."

    [[params.skills]]
      icon = "fa-music"
      title = "Music"
      description = "I play cello, piano, and sing bass in choir"
      
  # infos section
  [params.infos]
    enable = true
    title = "One more thing"
    description = "Along with playing cello and piano for many years, I also taught for three years at the Roseville District Summer Orchestra Camp, between 9th, 10th and 11th grade; I served as an assistant and instuctor for students ranging from 3-4th grade beginners to advanced students entering high school, helping teach music theory and performance skills and techniques. In addition to teaching, I myself have taken several courses studying music theory. If anyone in the Roseville or Sarasota area would be interested in beginner cello or music tutoring, please feel free to contact me. Additionally, If anyone would be interested in my performance services, please fill out the contact form below, and I will email you back as soon as possible. In addition to small and large ensembles, I have substantial solo performance and accompaniment experience for both cello and piano."
    # the picture is stored at static/images/
    picture = "black_and_white_cello_profile.jpg"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = true
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "none"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "none"
        link = "#"

      [[params.footer.social]]
        title = "LinkedIn"
        icon = "fa-linkedin"
        link = "https://www.linkedin.com/in/adam-reinschmidt-920355158"

      [[params.footer.social]]
        title = "Dribbble"
        icon = "none"
        link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "none"
        link = "#"
      
      [[params.footer.social]]
        title = "Instagram"
        icon = "none"
        link = "#"
      
    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© 2018 Adam Reinschmidt."

      [[params.footer.copyright.notice]]
        text = "Design: [HTML5UP](//html5up.net)"

      [[params.footer.copyright.notice]]
        text = "Demo Images: [Unsplash](//unsplash.com/)"
