# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Highlights"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Font-Awesome's icon font. Look at fontawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engines. Feel free to add more information.
  # These lines will be inserted as meta tags.
  name = "Your Name"
  description = "Your Description"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "your@mail.com"

  # If this param is set to true, every section gets its own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.png and overlay.png to set the background.
  backgroundpersection = true

  # Hero Section
  [params.hero]
    title = "Highlights"
    description = "a fun little { responsive } single Pager by [HTML5UP](//html5up.net)"
    buttontext = "begin"

  # about section
  [params.about]
    enable = true
    title = "Who am I"
    description = "My name is Adam Reinschmidt, and I am a cellist and student at Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "adam_grad_cello.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "Stuff I do"
    description = "Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet vulputate."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "pic02.jpg"

    [[params.skills]]
      icon = "fa-university"
      title = "Magna Etiam"
      description = "New College of Florida"

    [[params.skills]]
      icon = "fa-pencil"
      title = "Lorem Ipsum"
      description = "student teacher"

    [[params.skills]]
      icon = "fa-code"
      title = "Nulla Tempus"
      description = "a little R + web design EXP (as evidenced by the existence of this site)"

    [[params.skills]]
      icon = "fa-music"
      title = "Sed Feugiat"
      description = "play cello, piano, and sing in choir"
      
  # infos section
  [params.infos]
    enable = true
    title = "One more thing"
    description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
    # the picture is stored at static/images/
    picture = "pic03.jpg"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = true
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "#"

      [[params.footer.social]]
        title = "Instagramm"
        icon = "fa-instagram"
        link = "#"

      [[params.footer.social]]
        title = "Dribbble"
        icon = "fa-dribbble"
        link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "#"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© 2018 Adam Reinschmidt."

      [[params.footer.copyright.notice]]
        text = "Design: [HTML5UP](//html5up.net)"

      [[params.footer.copyright.notice]]
        text = "Demo Images: [Unsplash](//unsplash.com/)"
